#!/bin/bash

# Script to connect to Clemson's Cisco VPN
# to disconnect daily at 18:00:
# SHELL=/bin/bash
# 00   18 *   *   *   root /usr/bin/killall openconnect
# or copy crontab.d/killVpn to /etc/crontab.d

HOST='cuvpn.clemson.edu'
SCRIPT="${HOME}/bin/vpnc-script"

if [[ "cudrvpn" == "${0##*/}" ]]; then
        HOST='cudrvpn.clemson.edu'
fi

sudo openconnect --script=${SCRIPT} --user=eckard ${HOST} --timestamp --deflate
